name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Quiz 1
      id: quiz-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Quiz 1
        setup-command: ''
        command: Which of the following best describes software engineering?
        input: |-
          a) The study of hardware components
          b) The process of designing, developing, and maintaining software
          c) The analysis of networking protocols
          d) The management of data storage systems
        expected-output:
        SE_Day1_Assignment

#Part 1: Introduction to Software Engineering

Explain what software engineering is and discuss its importance in the technology industry. 

Identify and describe at least three key milestones in the evolution of software engineering.  

List and briefly explain the phases of the Software Development Life Cycle.

Compare and contrast the Waterfall and Agile methodologies. Provide examples of scenarios where each would be appropriate.

Describe the roles and responsibilities of a Software Developer, a Quality Assurance Engineer, and a Project Manager in a software engineering team.

Discuss the importance of Integrated Development Environments (IDEs) and Version Control Systems (VCS) in the software development process. Give examples of each.

What are some common challenges faced by software engineers? Provide strategies to overcome these challenges.

Explain the different types of testing (unit, integration, system, and acceptance) and their importance in software quality assurance.

#Part 2: Introduction to AI and Prompt Engineering

Define prompt engineering and discuss its importance in interacting with AI models.

Provide an example of a vague prompt and then improve it by making it clear, specific, and concise. Explain why the improved prompt is more effective.



Part 1: Introduction to Software Engineering

1. What is Software Engineering and its Importance?
Software engineering is the process of developing and maintaining software.

2. Key Milestones in the Evolution of Software Engineering
1968 - The Birth of Software Engineering: The term software engineering was first introduced at the NATO Software Engineering Conference, marking the recognition of software development as an engineering discipline.
1970 - Waterfall Model Introduction Winston W. Royce proposed the Waterfall Model, a structured approach to software development with sequential phases.
2001 - Agile Manifesto: The Agile Manifesto revolutionized software development by introducing flexible and iterative methodologies, improving collaboration and adaptability in software projects.

3. Phases of the Software Development Life Cycle (SDLC)
1. Requirement Analysis: Gathering and defining the project’s needs.
2. Planning: Defining scope, timeline, and resources.
3. Design: Creating architecture and system design.
4. Implementation (Coding): Writing the actual software code.
5. Testing: Ensuring the software is functional and bug-free.
6. Deployment: Releasing the software for use.
7. Maintenance:Updating and fixing software over time.

4. Waterfall vs. Agile Methodologies**
Feature           Waterfall                         Agile 

Approach          Sequential and linear             Iterative and flexible 
 Changes          Difficult to accommodate           Easy to adapt 
 Documentation    Extensive upfront documentation    Minimal, adaptive documentation 
 Collaboration    Limited to specific phases             Continuous collaboration among teams 

Examples
- Waterfall is best for: Projects with well-defined requirements, such as government or banking software.
- Agile is best for: Dynamic projects like mobile app development, where continuous feedback and iterations are required.

5. Roles in a Software Engineering Team
- Software Developer: Writes and maintains code, implements features, and ensures performance.
- Quality Assurance (QA) Engineer:Tests software to identify bugs and ensures quality standards.
- Project Manager: Oversees project timelines, resource allocation, and communication among stakeholders.
6. Importance of IDEs and Version Control Systems
- Integrated Development Environments (IDEs): Provide tools like code editors, debuggers, and compilers to streamline development. *Examples: Visual Studio Code, PyCharm.
- Version Control Systems (VCS):Manage code changes and enable collaboration. Examples: Git (GitHub, GitLab, Bitbucket).

7. Common Challenges Faced by Software Engineers & Solutions
- Bug Fixing: Use debugging tools and maintain clear documentation.
- Scope Creep: Implement proper project management and Agile practices.
- Keeping Up with Technology:Engage in continuous learning through courses and community involvement.

8. Types of Software Testing and Their Importance
-Unit Testing:Tests individual components for functionality.
-Integration Testing: Ensures different modules work together correctly.
-System Testing:Verifies the entire system's performance and behavior.
Acceptance Testing: Confirms the software meets business requirements and user expectations.

Part 2: Introduction to AI and Prompt Engineering

1. What is Prompt Engineering?
Prompt engineering is the practice of crafting effective prompts to optimize interactions with AI models.
2. Improving a Prompt Example
- Vague Prompt-Tell me about AI.
- Improved Prompt Explain artificial intelligence, its key components, and its impact on industries like healthcare and finance
- Why is it better? The improved prompt is specific, structured, and directs the AI toward a more detailed and relevant response


        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        QUIZ-1_RESULTS: "${{steps.quiz-1.outputs.result}}"
      with:
        runners: quiz-1
